### ISSUE TITLE
Brief question

### ISSUE THREAD

**Issue by Bui892893knm** [realityquintupled/LIV-CustomPathCameraBehaviour-Editor#1]
Hey, 

sorry for reaching out to you this way. 

I would like to know whether it is possible to have a kind of custom 360 degree camera in order to record 360 degree gameplay.

Would be great if you can help here. 

All the best! :-)

**Comment by realityquintupled** [comment]
Hi,

I'm not entirely sure what you're asking for. If you're looking for something that outputs 360° video, that is outside my scope of expertise, sorry.
